ProjetWeb/src/Entity/Social/Event.php
<?php

namespace App\Entity\Social;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 * @Vich\Uploadable()
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="event_image", fileNameProperty="event_image_path")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Length(min="3", max="50")
     */
    private $event_name;

    /**
     * @ORM\Column(type="text")
     */
    private $event_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min="3", max="255")
     */
    private $event_image_path;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Length(min="3", max="255")
     */
    private $event_location;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(min="0", max="100")
     */
    private $event_price;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $event_date;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $event_created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $event_modified_at;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $event_created_by;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\PositiveOrZero
     */
    private $event_is_visible;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $event_period;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Social\EventType", inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $event_type;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Social\Picture", mappedBy="event", orphanRemoval=true)
     */
    private $pictures;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Social\Participation", mappedBy="event", orphanRemoval=true)
     */
    private $participation;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Social\Impression", inversedBy="events")
     */
    private $impression;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->participation = new ArrayCollection();
        $this->impression = new ArrayCollection();
        $this->event_created_at = new \DateTime();
        $this->event_created_by = 1;
        $this->event_is_visible = 1;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEventName(): ?string
    {
        return $this->event_name;
    }

    public function setEventName(string $event_name): self
    {
        $this->event_name = $event_name;

        return $this;
    }

    public function getEventDescription(): ?string
    {
        return $this->event_description;
    }

    public function setEventDescription(string $event_description): self
    {
        $this->event_description = $event_description;

        return $this;
    }

    public function getEventImagePath(): ?string
    {
        return $this->event_image_path;
    }

    public function setEventImagePath(string $event_image_path): self
    {
        $this->event_image_path = $event_image_path;

        return $this;
    }

    public function getEventLocation(): ?string
    {
        return $this->event_location;
    }

    public function setEventLocation(string $event_location): self
    {
        $this->event_location = $event_location;

        return $this;
    }

    public function getEventPrice(): ?int
    {
        return $this->event_price;
    }

    public function setEventPrice(?int $event_price): self
    {
        $this->event_price = $event_price;

        return $this;
    }

    public function getEventDate(): ?\DateTimeInterface
    {
        return $this->event_date;
    }

    public function setEventDate(\DateTimeInterface $event_date): self
    {
        $this->event_date = $event_date;

        return $this;
    }

    public function getEventCreatedAt(): ?\DateTimeInterface
    {
        return $this->event_created_at;
    }

    public function setEventCreatedAt(\DateTimeInterface $event_created_at): self
    {
        $this->event_created_at = $event_created_at;

        return $this;
    }

    public function getEventModifiedAt(): ?\DateTimeInterface
    {
        return $this->event_modified_at;
    }

    public function setEventModifiedAt(?\DateTimeInterface $event_modified_at): self
    {
        $this->event_modified_at = $event_modified_at;

        return $this;
    }

    public function getEventCreatedBy(): ?int
    {
        return $this->event_created_by;
    }

    public function setEventCreatedBy(int $event_created_by): self
    {
        $this->event_created_by = $event_created_by;

        return $this;
    }

    public function getEventIsVisible(): ?bool
    {
        return $this->event_is_visible;
    }

    public function setEventIsVisible(bool $event_is_visible): self
    {
        $this->event_is_visible = $event_is_visible;

        return $this;
    }

    public function getEventType(): ?EventType
    {
        return $this->event_type;
    }

    public function setEventType(?EventType $event_type_id): self
    {
        $this->event_type = $event_type_id;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setEvent($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getEvent() === $this) {
                $picture->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Participation[]
     */
    public function getParticipation(): Collection
    {
        return $this->participation;
    }

    public function addParticipation(Participation $event): self
    {
        if (!$this->participation->contains($event)) {
            $this->participation[] = $event;
            $event->setEvent($this);
        }

        return $this;
    }

    public function removeParticipation(Participation $event): self
    {
        if ($this->participation->contains($event)) {
            $this->participation->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getEvent() === $this) {
                $event->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Impression[]
     */
    public function getImpression(): Collection
    {
        return $this->impression;
    }

    public function addImpression(Impression $impression): self
    {
        if (!$this->impression->contains($impression)) {
            $this->impression[] = $impression;
        }

        return $this;
    }

    public function removeImpression(Impression $impression): self
    {
        if ($this->impression->contains($impression)) {
            $this->impression->removeElement($impression);
        }

        return $this;
    }

    public function getEventPeriod(): ?string
    {
        return $this->event_period;
    }

    public function setEventPeriod(?string $event_period): self
    {
        $this->event_period = $event_period;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Event
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile): Event
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->event_modified_at = new \DateTime('now');
        }
        return $this;
    }



}

ProjetWeb/src/Entity/Social/Picture.php
<?php

namespace App\Entity\Social;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\{File, UploadedFile};
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PictureRepository")
 * @Vich\Uploadable()
 */
class Picture
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Assert\Length(max="50")
     */
    private $picture_name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $picture_description;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $picture_posted_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $picture_modified_at;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="picture_image", fileNameProperty="picture_path")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="10", max="255")
     */
    private $picture_path;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $picture_user_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Social\Event", inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $event;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Social\Comment", mappedBy="picture", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Social\Impression", inversedBy="pictures")
     */
    private $impression;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_visible;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->impression = new ArrayCollection();

        $this
            ->setPicturePostedAt(new \DateTime())
            ->setIsVisible(1);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPictureName(): ?string
    {
        return $this->picture_name;
    }

    public function setPictureName(?string $picture_name): self
    {
        $this->picture_name = $picture_name;

        return $this;
    }

    public function getPictureDescription(): ?string
    {
        return $this->picture_description;
    }

    public function setPictureDescription(?string $picture_description): self
    {
        $this->picture_description = $picture_description;

        return $this;
    }

    public function getPicturePostedAt(): ?\DateTimeInterface
    {
        return $this->picture_posted_at;
    }

    public function setPicturePostedAt(\DateTimeInterface $picture_posted_at): self
    {
        $this->picture_posted_at = $picture_posted_at;

        return $this;
    }

    public function getPictureModifiedAt(): ?\DateTimeInterface
    {
        return $this->picture_modified_at;
    }

    public function setPictureModifiedAt(?\DateTimeInterface $picture_modified_at): self
    {
        $this->picture_modified_at = $picture_modified_at;

        return $this;
    }

    public function getPicturePath(): ?string
    {
        return $this->picture_path;
    }

    public function setPicturePath(string $picture_path): self
    {
        $this->picture_path = $picture_path;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Picture
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile): Picture
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile){
            $this->picture_modified_at = new \DateTime();
        }
        return $this;
    }

    public function getPictureUserId(): ?int
    {
        return $this->picture_user_id;
    }

    public function setPictureUserId(int $picture_user_id): self
    {
        $this->picture_user_id = $picture_user_id;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event_id): self
    {
        $this->event = $event_id;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPicture($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPicture() === $this) {
                $comment->setPicture(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Impression[]
     */
    public function getImpression(): Collection
    {
        return $this->impression;
    }

    public function addImpression(Impression $impression): self
    {
        if (!$this->impression->contains($impression)) {
            $this->impression[] = $impression;
        }

        return $this;
    }

    public function removeImpression(Impression $impression): self
    {
        if ($this->impression->contains($impression)) {
            $this->impression->removeElement($impression);
        }

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): self
    {
        $this->is_visible = $is_visible;

        return $this;
    }
}

ProjetWeb/src/Form/PictureType.php
<?php

namespace App\Form;

use App\Entity\Social\Picture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PictureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('picture_name')
            ->add('picture_description', TextareaType::class, [
                'required' => false
            ])
            ->add('imageFile', FileType::class, [
                'label' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Picture::class,
            'translation_domain' => 'forms'
        ]);
    }
}

ProjetWeb/templates/pictures/new.html.twig
{% extends 'base.html.twig' %}

{% block title 'Nouvelle illustration d\'événement | BDE-CESI' %}

{% block body %}
<h1>Ajouter une illustration à l'événement</h1>
<div class="form">
    {{ form_start(form) }}
        <div class="group off">{{ form_row(form.picture_name) }}</div>
        <div class="group off">{{ form_row(form.picture_description) }}</div>
        <div class="group off">{{ form_row(form.imageFile) }}</div>
        {{ form_rest(form) }}
        <button type="submit" class="contained">AJOUTER</button>
    {{ form_end(form) }}
</div>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/form.js') }}"></script>
{% endblock %}

ProjetWeb/templates/pictures/show.html.twig
{% extends 'base.html.twig' %}

{% block title 'Illustration d\'événement "' ~ picture.pictureName ~ '" | BDE-CESI' %}


{% block body %}
    <h1>Illustration d'événement</h1>

    <section>
        <div class="row">
            <div>
                <img src="{{ picture.picturePath }}" alt="">
            </div>
            <div class="p">{{ picture.pictureDescription }}</div>
        </div>
        <div class="section_footer row likes">
            {% if action == 'like' %}
                <a href="{{ path('pictures.like', {id: picture.id}) }}" class="option active"><i class="material-icons">thumb_up</i><span>{{ count_like }}</span></a>
                <a href="{{ path('pictures.dislike', {id: picture.id}) }}" class="option"><i class="material-icons">thumb_down</i><span>{{ count_dislike }}</span></a>
            {% elseif action == 'dislike' %}
                <a href="{{ path('pictures.like', {id: picture.id}) }}" class="option"><i class="material-icons">thumb_up</i><span>{{ count_like }}</span></a>
                <a href="{{ path('pictures.dislike', {id: picture.id}) }}" class="option active"><i class="material-icons">thumb_down</i><span>{{ count_dislike }}</span></a>
            {% else %}
                <a href="{{ path('pictures.like', {id: picture.id}) }}" class="option"><i class="material-icons">thumb_up</i><span>{{ count_like }}</span></a>
                <a href="{{ path('pictures.dislike', {id: picture.id}) }}" class="option"><i class="material-icons">thumb_down</i><span>{{ count_dislike }}</span></a>
            {% endif %}
        </div>
    </section>

    <div class="row">
        <div class="flex-1 column" style="margin-right: 8px">
            <h2>Evénement</h2>
            <div class="card">
                <div class="card_header">{{ picture.event.eventName }}</div>
                <div class="card_body"></div>
                <div class="card_footer">
                    <p>Date de l'événement : {{ picture.event.eventDate | date('d-m-Y H:i') }}</p>
                    <a href="{{ path('events.show', {id: picture.event.id}) }}" class="contained">VOIR</a>
                </div>
            </div>
        </div>
        <div class="flex-3 column">
            <h2>Autres photos de l'événement</h2>
            <div class="grid-3">
                {% for picture in picturesRelated %}
                    <div class="card">
                        <div class="card_header">{{ picture.pictureName }}</div>
                        <div class="card_body">
                            <img src="{{ picture.picturePath }}" alt="">
                        </div>
                        <div class="card_footer">
                            <a href="{{ path('pictures.show', {id: picture.id}) }}" class="contained">VOIR</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="column">
        <h2>Commentaires :</h2>
        {% for comment in comments %}
            <div class="comment card" style="margin-bottom: 16px">
                <div class="row">
                    <div>
                        <img src="https://dummyimage.com/200x200/000/fff" alt="" class="comment_img">

                    </div>
                    <div>
                        {% if comment.commentModifiedAt is null %}
                            <p>Ajouté le : {{ comment.commentPostedAt | date('d-m-Y H:i:s') }}</p>
                        {% else %}
                            <p>Modifié le : {{ comment.commentModifiedAt | date('d-m-Y H:i:s') }}</p>
                        {% endif %}
                        <span class="separate_content"></span>
                        <p>{{ comment.commentText }}</p>
                    </div>
                </div>
                <div class="row" style="padding: 8px">
                    <!--<a href="" class="option"><i class="material-icons">thumb_up</i></a>
                    <a href="" class="option"><i class="material-icons">thumb_down</i></a>-->
                    {% if is_granted('ROLE_MODO') %}
                        {% if comment.isVisible == 1 %}
                            <form method="post" action="{{ path('admin.comments.delete', {id: comment.id}) }}">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
                                <button class="contained danger">SUPPRIMER</button>
                            </form>
                        {% else %}
                            <button disabled class="disabled">SUPPRIMÉ</button>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        {% if app.user %}
            <div class="add_comment">
                {{ form_start(form) }}
                    <div class="group off">{{ form_row(form.commentText) }}</div>
                    <button type="submit" class="contained">AJOUTER</button>
                {{ form_end(form) }}
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/ajaxLikes.js') }}"></script>
    <script src="{{ asset('assets/js/form.js') }}"></script>
{% endblock %}