ProjetWeb/src/Entity/Social/Event.php
<?php

namespace App\Entity\Social;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 * @Vich\Uploadable()
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="event_image", fileNameProperty="event_image_path")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Length(min="3", max="50")
     */
    private $event_name;

    /**
     * @ORM\Column(type="text")
     */
    private $event_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min="3", max="255")
     */
    private $event_image_path;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Length(min="3", max="255")
     */
    private $event_location;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(min="0", max="100")
     */
    private $event_price;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $event_date;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $event_created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $event_modified_at;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $event_created_by;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\PositiveOrZero
     */
    private $event_is_visible;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $event_period;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Social\EventType", inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $event_type;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Social\Picture", mappedBy="event", orphanRemoval=true)
     */
    private $pictures;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Social\Participation", mappedBy="event", orphanRemoval=true)
     */
    private $participation;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Social\Impression", inversedBy="events")
     */
    private $impression;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->participation = new ArrayCollection();
        $this->impression = new ArrayCollection();
        $this->event_created_at = new \DateTime();
        $this->event_created_by = 1;
        $this->event_is_visible = 1;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEventName(): ?string
    {
        return $this->event_name;
    }

    public function setEventName(string $event_name): self
    {
        $this->event_name = $event_name;

        return $this;
    }

    public function getEventDescription(): ?string
    {
        return $this->event_description;
    }

    public function setEventDescription(string $event_description): self
    {
        $this->event_description = $event_description;

        return $this;
    }

    public function getEventImagePath(): ?string
    {
        return $this->event_image_path;
    }

    public function setEventImagePath(string $event_image_path): self
    {
        $this->event_image_path = $event_image_path;

        return $this;
    }

    public function getEventLocation(): ?string
    {
        return $this->event_location;
    }

    public function setEventLocation(string $event_location): self
    {
        $this->event_location = $event_location;

        return $this;
    }

    public function getEventPrice(): ?int
    {
        return $this->event_price;
    }

    public function setEventPrice(?int $event_price): self
    {
        $this->event_price = $event_price;

        return $this;
    }

    public function getEventDate(): ?\DateTimeInterface
    {
        return $this->event_date;
    }

    public function setEventDate(\DateTimeInterface $event_date): self
    {
        $this->event_date = $event_date;

        return $this;
    }

    public function getEventCreatedAt(): ?\DateTimeInterface
    {
        return $this->event_created_at;
    }

    public function setEventCreatedAt(\DateTimeInterface $event_created_at): self
    {
        $this->event_created_at = $event_created_at;

        return $this;
    }

    public function getEventModifiedAt(): ?\DateTimeInterface
    {
        return $this->event_modified_at;
    }

    public function setEventModifiedAt(?\DateTimeInterface $event_modified_at): self
    {
        $this->event_modified_at = $event_modified_at;

        return $this;
    }

    public function getEventCreatedBy(): ?int
    {
        return $this->event_created_by;
    }

    public function setEventCreatedBy(int $event_created_by): self
    {
        $this->event_created_by = $event_created_by;

        return $this;
    }

    public function getEventIsVisible(): ?bool
    {
        return $this->event_is_visible;
    }

    public function setEventIsVisible(bool $event_is_visible): self
    {
        $this->event_is_visible = $event_is_visible;

        return $this;
    }

    public function getEventType(): ?EventType
    {
        return $this->event_type;
    }

    public function setEventType(?EventType $event_type_id): self
    {
        $this->event_type = $event_type_id;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setEvent($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getEvent() === $this) {
                $picture->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Participation[]
     */
    public function getParticipation(): Collection
    {
        return $this->participation;
    }

    public function addParticipation(Participation $event): self
    {
        if (!$this->participation->contains($event)) {
            $this->participation[] = $event;
            $event->setEvent($this);
        }

        return $this;
    }

    public function removeParticipation(Participation $event): self
    {
        if ($this->participation->contains($event)) {
            $this->participation->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getEvent() === $this) {
                $event->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Impression[]
     */
    public function getImpression(): Collection
    {
        return $this->impression;
    }

    public function addImpression(Impression $impression): self
    {
        if (!$this->impression->contains($impression)) {
            $this->impression[] = $impression;
        }

        return $this;
    }

    public function removeImpression(Impression $impression): self
    {
        if ($this->impression->contains($impression)) {
            $this->impression->removeElement($impression);
        }

        return $this;
    }

    public function getEventPeriod(): ?string
    {
        return $this->event_period;
    }

    public function setEventPeriod(?string $event_period): self
    {
        $this->event_period = $event_period;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Event
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile): Event
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->event_modified_at = new \DateTime('now');
        }
        return $this;
    }



}

ProjetWeb/src/Entity/Social/EventType.php
<?php

namespace App\Entity\Social;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventTypeRepository")
 */
class EventType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\Length(min="3", max="25")
     */
    private $event_type_name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Social\Event", mappedBy="event_type")
     */
    private $events;

    public function __construct()
    {
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEventTypeName(): ?string
    {
        return $this->event_type_name;
    }

    public function setEventTypeName(string $event_type_name): self
    {
        $this->event_type_name = $event_type_name;

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setEventType($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getEventType() === $this) {
                $event->setEventType(null);
            }
        }

        return $this;
    }
}

ProjetWeb/src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Social\Event;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\{DateTimeType, DateType, FileType, NumberType};
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Social\EventType as Category;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('event_name')
            ->add('event_description')
            ->add('imageFile', FileType::class, [
                'required' => false,
                'label' => false
            ])
            ->add('event_location')
            ->add('event_price', NumberType::class)
            ->add('event_date', DateTimeType::class)
            ->add('event_type', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'eventTypeName'
            ])
            //->add('event_period')
            //->add('event_type', ChoiceType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
            'translation_domain' => 'forms'
        ]);
    }
}

ProjetWeb/templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Les événements | BDE.CESI' %}

{% block body %}

    <div class="row justify_between">
        <h1>Les événements</h1>
        <div class="row">
            {% if app.user %}
                <a href="{{ path('profile.events') }}" class="contained_no-width">MES INSCRIPTIONS</a>
            {% endif %}
            {% if is_granted('ROLE_ADMIN') %}
                <span class="separate_buttons"></span>
                <span class="separate_buttons"></span>
                <a href="{{ path('admin.events.new') }}" class="contained_no-width"><i class="material-icons">add</i> NOUVEL ÉVÉNEMENT</a>
            {% endif %}
        </div>
    </div>
    <section>
        <div class="search_type" style="margin-bottom: 32px">
            <h3>Personnaliser la recherche</h3>
            <div class="row justify_between align_center">
                <div class="grower" style="width: initial">
                    {{ form_start(form) }}
                    <div class="group off half">
                        {{ form_row(form.maxPrice) }}
                    </div>
                    <div class="group half select">
                        {{ form_rest(form) }}
                    </div>
                </div>
                <div>
                    <button type="submit" class="contained_no-width"><i class="material-icons">search</i></button>
                    {{ form_end(form) }}
                </div>

            </div>
        </div>
        <div class="product-container">
            {% for event in events %}
                <article class="product">
                    <div class="product-name">{{ event.eventName }}</div>
                    <div class="resize_img">
                        <img src="{{ vich_uploader_asset(event, 'imageFile') }}" alt="">
                    </div>
                    <p class="event_date">Date : {{ event.eventDate | date('d-m-Y') }}
                        à {{ event.eventDate | date('H:i') }}</p>
                    <div class="product-price" style="padding-bottom: 112px">
                        {{ event.eventPrice }}€
                    </div>
                    <div class="sticky_bottom">
                        {% set participated = false %}
                        {% if app.user and event.eventDate > today %}
                            {% for participation in participations %}
                                {% if participation.event.id == event.id %}
                                    {% set participated = true %}
                                {% endif %}
                            {% endfor %}
                            {% if participated == true %}
                                <a href="" class="blue disabled" disabled>INSCRIT</a>
                            {% else %}
                                <a href="{{ path('events.participate', {id: event.id}) }}"
                                   class="contained">S'INSCRIRE</a>
                            {% endif %}
                        {% endif %}
                        <a href="{{ path('events.show', {id: event.Id}) }}" class="link">Voir</a>
                    </div>
                </article>
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(events) }}
        </div>
    </section>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/form.js') }}"></script>
{% endblock %}

ProjetWeb/templates/events/show.html.twig
{% extends 'base.html.twig' %}

{% block title 'Evénement | ' ~ event.eventName %}

{% block body %}
    <h1>Evénement - {{ event.eventName }}</h1>

    <section>
        <article class="flex-3 column">
            <div class="card_body row">
                <div>
                    {% if event.eventImagePath %}
                        <img src="{{ vich_uploader_asset(event, 'imageFile') }}" alt="">
                    {% endif %}
                </div>
                <div>
                    <p>{{ event.eventDescription }}</p>
                </div>
            </div>
            <div class="event_option">
                <p style="margin-bottom: 0">Prix : {{ event.eventPrice }} €</p>
                <p style="margin-top: 0">Type de l'événement :
                    <a href="{{ path('events.index') }}?category={{ event.eventType.id }}">{{ event.eventType.eventTypeName }}</a>
                </p>
                <div class="row likes">
                    {% if action == 'like' %}
                        <a href="{{ path('events.like', {id: event.id}) }}" class="option active"><i class="material-icons">thumb_up</i><span>{{ count_like }}</span></a>
                        <a href="{{ path('events.dislike', {id: event.id}) }}" class="option"><i class="material-icons">thumb_down</i><span>{{ count_dislike }}</span></a>
                    {% elseif action == 'dislike' %}
                        <a href="{{ path('events.like', {id: event.id}) }}" class="option"><i class="material-icons">thumb_up</i><span>{{ count_like }}</span></a>
                        <a href="{{ path('events.dislike', {id: event.id}) }}" class="option active"><i
                                    class="material-icons">thumb_down</i><span>{{ count_dislike }}</span></a>
                    {% else %}
                        <a href="{{ path('events.like', {id: event.id}) }}" class="option"><i class="material-icons">thumb_up</i><span>{{ count_like }}</span></a>
                        <a href="{{ path('events.dislike', {id: event.id}) }}" class="option"><i class="material-icons">thumb_down</i><span>{{ count_dislike }}</span></a>
                    {% endif %}
                </div>
                <div class="participation">
                    {% if has_participated == true %}
                        {% if event.eventDate > today %}
                            <a href="#" class="disabled">INSCRIT</a>
                        {% else %}
                            <a href="{{ path('pictures.new', {event: event.id}) }}" class="contained<"><i class="material-icons">add</i>AJOUTER UNE PHOTO</a>
                        {% endif %}
                    {% else %}
                        <a href="{{ path('events.participate', {id: event.id}) }}" class="contained_no-width">S'INSCRIRE</a>
                    {% endif %}
                </div>
            </div>
        </article>
    </section>
    <section>
        <h2>Images : </h2>
        <div class="grid-4">
            {% for picture in event.pictures %}
                <div class="card">
                    <div class="card_body">
                        <img src="{{ vich_uploader_asset(picture, 'imageFile') }}" alt="">
                    </div>
                    <div class="card_footer">
                        <a href="{{ path('pictures.show', {'id': picture.id}) }}" class="contained">COMMENTER</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/ajaxLikes.js') }}"></script>
{% endblock %}